# Site title and subtitle. This is used in _includes/header.html
title: "Tech'n'Tuts"
subtitle: "PAWM International's Documentation Platform"

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/pawmint/techntuts'

# Default categories (in order) to appear in the navigation
sections: [
    ['web', 'WebApp Side'],
    ['home', 'Home Side'],
    ['tools', 'Tools & Methods'],
    ['deploy', 'Deployment'],
    ['admin', 'Admin'],
    ['misc', 'Miscellaneous']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/techntuts'

# Dates are not included in permalinks
permalink: /:title/

# Syntax highlighting
highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
